from totest.views.index import *
from totest.views.api_settings import *
from totest.views.api_mock import *
from totest.views.tool_cnumber import *
from totest.views.tool_drink_calc import *
from totest.views.get_sms import *
from totest.views.iwater_api import *
from totest.views.mock_shift import *
from totest.views.mock_any_api_manual import *
