# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_mock',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=50, null=True)),
                ('api_resp_json', models.TextField(null=True)),
            ],
        ),
    ]
