# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drink_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_plan', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('weight', models.CharField(max_length=10, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('job', models.CharField(max_length=10, null=True)),
                ('distance_days', models.CharField(max_length=10, null=True)),
                ('birth_days', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hydrating_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydrating_plan', models.CharField(max_length=10, null=True)),
                ('decrement_weight', models.CharField(max_length=10, null=True)),
                ('sports_type', models.CharField(max_length=10, null=True)),
                ('sports_distance', models.CharField(max_length=10, null=True)),
                ('temperature', models.CharField(max_length=10, null=True)),
                ('water', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
