# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totest', '0004_iwater_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='mock_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.CharField(max_length=10)),
            ],
        ),
    ]
