# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totest', '0005_mock_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_mock',
            name='is_open',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
